name: Quick iOS Build
on: [schedule, workflow_dispatch, push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - run: git clone https://github.com/mineek/kfdfunv4 && cd kfdfun4 && sudo make -C ChOma install && mkdir -p ~/.local/bin && cp ChOma/output/tests/* ~/.local/bin && make -C tools && cp tools/insert_dylib ~/.local/bin && ./app/build.sh
    - uses: actions/create-release@v1
      with: 
        tag_name: ${{ github.run_id }}
        release_name: 'Release ${{ github.run_id }}'
        draft: false

    - uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./app/packages/kfdmineek.tipa
        asset_name: kfdmineek.tipa
        asset_content_type: application/octet-stream
